### ISSUE TITLE
PowerBI report is not showing any data

### ISSUE THREAD

**Issue by srushti-714** [solliancenet/azure-synapse-analytics-day#10]
After creating the PowerBI dataset in Exercise 3 task 1
In exercise 3 task 2 the Powerbi report is not showing up any data
Can you please check on this as soon as possible?
![pbi](https://user-images.githubusercontent.com/55180169/83140871-6090c000-a10c-11ea-9063-30751a93e9a2.jpg)

**Comment by srushti-714** [comment]
Can you please add the instruction in Exercise 3 task 2
if directquery fails to show the data in powerbi workspace

The workaround is:
Navigate to www.powerbi.com->Settings->Datasets-> Datasource credentials

 
![1](https://user-images.githubusercontent.com/55180169/83143772-18739c80-a110-11ea-9388-c181d0b8b412.jpg)
![2](https://user-images.githubusercontent.com/55180169/83143781-1c072380-a110-11ea-9067-7858823d6fc6.jpg)

**Comment by daronyondem** [comment]
Hi @srushti-714 , Do you have an environment where I can test this?

**Comment by srushti-714** [comment]
Hi @Daron Yöndem<mailto:daron@solliance.net>

I will send environment details to your personal email address

Is daron@solliance.net<mailto:daron@solliance.net> your email address where I can send the details??

Thanks,
Srushti

**Comment by daronyondem** [comment]
Yes daron@solliance.net it is. Thanks.

**Comment by daronyondem** [comment]
Hi @srushti-714 

I was able to reproduce the issue. However, I had to go through another step to get to a resolution.

When I first landed in the datasets listing screen I did not see the dataset. I had to select the correct workspace before being able to select the dataset.

![image](https://user-images.githubusercontent.com/2984187/83261278-bffdd700-a1c3-11ea-821d-4e5a94beba82.png)

Do you agree that this should be added as a step into instructions as well?

Let me know what you think?

**Comment by srushti-714** [comment]
Yes please add the instructions to get the solution for this

**Comment by daronyondem** [comment]
Take a look at the changes in #12 and let me know if that's ok to merge.

**Comment by srushti-714** [comment]
Looks good.


After Under Authentication Method select OAuth2 and select Sign In.

Can you add a note to navigate back to Synapse workspace and continue with rest of the steps after refreshing .

Can you suggest on the SQL DW size for performing the lab?

**Comment by srushti-714** [comment]
Thank you for the quick update.

Yes please you can close the issue
