### ISSUE TITLE
Exercise 1 Task 2 Step 9

### ISSUE THREAD

**Issue by srushti-714** [solliancenet/azure-synapse-analytics-day#13]
EX1 task 2 step 9 : There are no options like x axis and y axis and we have new options like key values,aggregations etc
![ex1task2step9](https://user-images.githubusercontent.com/55180169/83727847-54a08300-a663-11ea-862e-21b6ab00d420.jpg)

Exercise 2 task 1 step 21-Screenshot update 
Select 1000 rows->100 rows
![ex2task1step21](https://user-images.githubusercontent.com/55180169/83727509-ccba7900-a662-11ea-92ab-8b13559fd595.jpg)
Exercise 2 task 2 step 26
Screenshot update
![ex2task2step26](https://user-images.githubusercontent.com/55180169/83727598-f4a9dc80-a662-11ea-8c6d-218999cf692c.jpg)

**Comment by daronyondem** [comment]
Hi @srushti-714 

To be able to track and discuss issues separately I suggest we keep these separate. For this round, I will separate issues for you.

**Comment by daronyondem** [comment]
I'm dedicating this issue to the first one you reported above. 

For the other issues, I created #14 and #15

**Comment by daronyondem** [comment]
Now that all issues are separated, I'm moving back to the first one you reported above.

As far as I can tell the screenshot you referred to does not belong to EX1 task 2 step 9. It belongs to EX1 task 2 step 10. If that's correct there is already an issue about it here #7  Do you agree?

**Comment by srushti-714** [comment]
Yes you are right it is ex 2 task 2 step 10

**Comment by daronyondem** [comment]
Ok, in that case, we do not need to keep this issue open. We have #7, #14 and #15 to track those separately. 

Thanks
