### ISSUE TITLE
Potential Instructions Update

### ISSUE THREAD

**Issue by daronyondem** [solliancenet/azure-synapse-analytics-day#16]
Extracted from #9 

The notebook has many values to be replaced which will already be done as a part of setup ,can you remove it from the instruction?

00-Setupworkspace
![image](https://user-images.githubusercontent.com/2984187/83969804-b159a300-a8da-11ea-9fd3-83f1eae66fc8.png)

**Comment by daronyondem** [comment]
I'm confused. Your message titles the screenshot as `00-Setupworkspace` but the screenshot looks from somewhere else. Can you give me more clarity about what has to change?

**Comment by srushti-714** [comment]
@daronyondem  nothing to change here ,you had added a instruction to add value of sqlpassword for bonus notebook in Exercise 2 which we are doing it as part of setup i.e 00.Setupworkspace so that instruction is not needed .

**Comment by daronyondem** [comment]
Is this about Step 5 in the Bonus challenge in Exercise 2? Double-checking. Do you want me to remove that step?

**Comment by srushti-714** [comment]
Yes please remove the step 5 of bonus challenge

**Comment by daronyondem** [comment]
Sure. Thanks for confirming. The change is now in the `revisions` branch. Once you approve #9 it will be live.
