### ISSUE TITLE
Update changes in the lab guide

### ISSUE THREAD

**Issue by srushti-714** [solliancenet/azure-synapse-analytics-day#2]
**Exercise 1 :task 1 step 10**
https://asadatalake02.dfs.core.windows.net/wwi/factsale-parquet/2012/Q1/*/*
to
Update to **your datalake storage account name** instead of asadatalake02

**Exercise 2 
task 1 19th step** - Update SELECT TOP 1000 rows to  SELECT TOP 100 rows  
task 2 step 5 -UI change
![image](https://user-images.githubusercontent.com/55180169/82636021-485a0600-9c1f-11ea-9176-6b4de7766878.png)
task 2 step 10- UI change
![image](https://user-images.githubusercontent.com/55180169/82636131-9c64ea80-9c1f-11ea-9500-b376fd581828.png)

task 4- To look closer at any individual stage, you can use the Job IDs drop-down to select the stage number. In this case, select the drop-down and choose 5 from the list.
Can we remove the instruction to select 5 particularly as few jobs may not be having job 5.

**Exercise 5 -** Can we add a note as
Note: An explicit whitelisting of the Synapse workspace is required to run PREDICT function queries. As part of the lab, you will not be able to run through this exercise. Please check with instructor to see if this is enabled in your lab.

**Comment by daronyondem** [comment]
Hi @srushti-714 Can you take a look at the changes in the master branch and let me know if it is safe to close this issue? Thanks.

**Comment by srushti-714** [comment]
Hi @daronyondem 
Sure you can close this issue, I have verified the changes.

Can you please look into the below issue:
https://github.com/solliancenet/azure-synapse-analytics-day/issues/4
