### ISSUE TITLE
Exercise 4 - High Performance Analysis with Azure Synapse SQL Pools

### ISSUE THREAD

**Issue by srushti-714** [solliancenet/azure-synapse-analytics-day#22]
The SQL Query takes execution time greater than 15 secs for wwi_perf.FactSale_Fast table and wwi_perf.FactSale_Slow .

And sometimes wwi_perf.FactSale_Fast table takes more execution time compared to wwi_perf.FactSale_Slow table

Is it something related to SQLPool DW size?

**Comment by dakhoff** [comment]
Thats because customerkey 0 has 30M rows. And other distributions has less than 200K rows
