### ISSUE TITLE
Exercise 4 correction

### ISSUE THREAD

**Issue by jamserra** [solliancenet/azure-synapse-analytics-day#26]
The mention wwi_perf.FactSale_Perf on the 3rd-to-last paragraph should be wwi_perf.FactSale_Fast.

Also, I think the statement "When our query needs to consolidate each customer's data, a lot of data movement will occur between the distributions." should be expanded on.  Why is there data movement?  Maybe mention because the fact table is joining with the dimension table and go into details.  But I'm not sure I understand why a fact table that is set to round robin would be slower when it's joining a replicated dimension table?

**Comment by joelhulen** [comment]
Addressed in latest round of updates.
