### ISSUE TITLE
Exercise 2 - Ingest Sales Data.ipynb - File is missing

### ISSUE THREAD

**Issue by gmkuk** [solliancenet/azure-synapse-analytics-day#34]
Hi,

There is no file for Exercise 2 - Ingest Sales Data.ipynb

Could you please load it into the repository?

Thanks!

Jan

**Comment by gmkuk** [comment]
Also the file for Ex. 01 - Exercise 1 - Read with Spark.ipynb is missing.

**Comment by gmkuk** [comment]
I guess one creates one during Labs.

But in the preparation phase there are some non-functional links to the files above.

**Comment by joelhulen** [comment]
We moved away from providing these files to having students create the notebooks themselves. One of the reasons we're doing this is because we want to limit the number of notebooks attendees must run, thereby avoiding the ~5-minute spinup of a new Spark session each time.
