### ISSUE TITLE
Naming of PowerBI dataset-Exercise 3 task 1

### ISSUE THREAD

**Issue by srushti-714** [solliancenet/azure-synapse-analytics-day#4]
If prompted to save your changes, select Save and provide a unique name having the format user_dataset_UNIQUEID (where UNIQUEID is the unique identifier which you retrieved from your username, as described above)

Users might be confused with different datasetname in task1 and 2 so can you please 
Update the name to wwifactsales in Exercise 3 task 1 step 11 as we are using the same name in ex3 task 2

**Comment by daronyondem** [comment]
@srushti-714 Let me know if the change is ok.

**Comment by srushti-714** [comment]
@Daron Yöndem<mailto:daron@solliance.net> Can we also update the screenshots for Ex3 task1 as few of the users are confused with that.

I will send the screenshots in next 1-2 hours. Is that fine?

**Comment by daronyondem** [comment]
Sure feel free to open a new issue with the new screenshots whenever you got them ready. I can make that happen for you 😉

**Comment by srushti-714** [comment]
Thank you 😊that’s great!
