### ISSUE TITLE
Issue in Exercise 2

### ISSUE THREAD

**Issue by anushabc** [solliancenet/azure-synapse-analytics-day#41]
In Exercise 2, Step 17, we have the following:

Observe the results in the output pane, and see how easy it was to use Spark notebooks to write data from Blob Storage into Azure Synapse Analytics.
![image](https://user-images.githubusercontent.com/66515706/125756689-41e35d29-6764-4a65-81a4-033b105522f9.png)

It should be Observe the results in the output pane, and see how easy it was to use Spark notebooks to read data from Blob Storage into Azure Synapse Analytics.

@daronyondem can you please check on this and let me know if I'm mistaken

**Comment by daronyondem** [comment]
Not really, but I understand the confusion if you look at this in isolation. In Step 10, the learner reads data from blobs and writing into the `wwi_staging.Sale` table using the **SQL Analytics connector** in Spark. In Step 17, the query reads data from  `wwi_staging.Sale` to showcase how easy it was in Step 10 to write data into Synapse Analytics. I will change the wording in the exercise in a moment to clarify this. Thanks for your attention to detail.
