### ISSUE TITLE
Issue in Exercise 5 Task 3

### ISSUE THREAD

**Issue by anushabc** [solliancenet/azure-synapse-analytics-day#43]
In **Exercise 5 Task 3 step 7** we are not able to select the existing cognitive service, even though cognitive service and linked service are present.  And also the UI got updated.

![image](https://user-images.githubusercontent.com/66515706/139803772-8e945dd9-5cf0-4f73-9d18-644c3a2e2e2c.png)

@daronyondem can you please have a look at this?

**Comment by joelhulen** [comment]
We are going to be updating all of these labs soon. In the meantime, @ciprianjichici can you please take a look at this?

**Comment by anushabc** [comment]
We created a cognitive service with kind Text Analytics and tried it out this worked for me. And in Exercise 5 Task 2 while running databricks notebook got the below error in cell 23. 

![image](https://user-images.githubusercontent.com/66515706/140513730-9ec88528-554a-47c4-ae69-ab79ba532a37.png)

We updated the code to include  target_opset=13 this worked 

![image](https://user-images.githubusercontent.com/66515706/140514191-0d2d1b08-ee8c-4284-b84b-2e938c2cace3.png)
